### ISSUE TITLE
Add an option to add the current Milestone when there is only one and without a due date.

### ISSUE THREAD

**Issue by andrewjswan** [benelan/milestone-action#253]
### Description

Add an option to add the current Milestone when there is only one and without a due date.
If there is more than one Milestone and this option is enabled, then either ignore the addition or add the first one (this is optional).

### Acceptance Criteria

One Milestone without due date, like: 
https://github.com/MediaPortal/MediaPortal-1/milestones

**Comment by andrewjswan** [comment]
Any news?

**Comment by benelan** [comment]
I should be able to finish this enhancement in the next week. The last few weeks were pretty hectic; thanks for your patience.

**Comment by benelan** [comment]
I just released `v3.1.0`, which adds the `single` option for this issue. See the readme for more info. I made sure to update the `v3` this time as well :sweat_smile: 

Thanks for the suggestion!
